version: 2

# Sphinx build configuration
sphinx:
  configuration: docs/source/conf.py  # Path to your conf.py file

# Python environment configuration
python:
  version: "3.8"  # Specify the Python version
  install:
    - requirements: requirements.txt  # Use your existing requirements file
