version: 2

# Build settings
sphinx:
  configuration: docs/source/conf.py  # Path to your conf.py file

# Python environment
python:
  version: "3.8"  # Specify the Python version
  install:
    - requirements: requirements.txt  # Install dependencies from requirements.txt
