version: 2

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py  # Adjust this if conf.py is in a different location

# Python environment
python:
  version: "3.9"  # Ensure this matches a valid Python version on Read the Docs
  install:
    - requirements: requirements.txt  # Ensure this file exists and lists all dependencies
